const ShopActionTypes = {
    FETCH_CUSTOMERS_START: 'FETCH_CUSTOMERS_START',
    FETCH_CUSTOMERS_SUCCESS: 'FETCH_CUSTOMERS_SUCCESS',
    FETCH_CUSTOMERS_FAILURE: 'FETCH_CUSTOMERS_FAILURE',
    FETCH_PRODUCTS_START: 'FETCH_PRODUCTS_START',
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',
};

export default ShopActionTypes;