const AlertActionTypes = {
    ALERT_NOTIFICATION_MESSAGE: 'ALERT_NOTIFICATION_MESSAGE',
    ALERT_NOTIFICATION_SUCCESS: 'ALERT_NOTIFICATION_SUCCESS',
    ALERT_NOTIFICATION_ERROR: 'ALERT_NOTIFICATION_ERROR',
    SET_ALERT_NOTIFICATION: 'SET_ALERT_NOTIFICATION',
    REMOVE_ALERT_NOTIFICATION: 'REMOVE_ALERT_NOTIFICATION',
    WATCH_ALERT_NOTIFICATIONS: 'WATCH_ALERT_NOTIFICATIONS',
};

export default AlertActionTypes;