const ProductActionTypes = {
    PRODUCT_ADD_START: 'PRODUCT_ADD_START',
    PRODUCT_ADD_SUCCESS: 'PRODUCT_ADD_SUCCESS',
    PRODUCT_ADD_FAILURE: 'PRODUCT_ADD_FAILURE',
    FETCH_PRODUCT_DETAIL_START: 'FETCH_PRODUCT_DETAIL_START',
    FETCH_PRODUCT_DETAIL_SUCCESS: 'FETCH_PRODUCT_DETAIL_SUCCESS',
    FETCH_PRODUCT_DETAIL_FAILURE: 'FETCH_PRODUCT_DETAIL_FAILURE',
};

export default ProductActionTypes;